apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.10.1.114
  labels:
    app: nextcloud
  name: nextcloud
spec:
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "https"
    port: 443
    protocol: TCP
    targetPort: 443
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nextcloud
  sessionAffinity: ClientIP
  type: LoadBalancer
