---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.10.1.117
  name: ingress-lb
  namespace: ingress
spec:
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "https"
    port: 443
    protocol: TCP
    targetPort: 443
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: nginx-ingress-microk8s
  sessionAffinity: ClientIP
  type: LoadBalancer
